export const TEXT_CASES = {
  RESPECT_CASE: 'respect_case',
  LOWERCASE: 'lowercase',
  UPPERCASE: 'uppercase',
  CAPITALIZE: 'capitalize',
  SNAKE_CASE: 'snake_case',
  CAMEL_CASE: 'camel_case',
};

export const TEXT_CASE_LABELS = {
  [TEXT_CASES.RESPECT_CASE]: 'Respect Case',
  [TEXT_CASES.LOWERCASE]: 'lowercase',
  [TEXT_CASES.UPPERCASE]: 'UPPERCASE',
  [TEXT_CASES.CAPITALIZE]: 'Capitalize Case',
  [TEXT_CASES.SNAKE_CASE]: 'snake_case',
  [TEXT_CASES.CAMEL_CASE]: 'camelCase',
};

export const TEXT_CASE_OPTIONS = [
  { value: TEXT_CASES.RESPECT_CASE, label: TEXT_CASE_LABELS[TEXT_CASES.RESPECT_CASE] },
  { value: TEXT_CASES.LOWERCASE, label: TEXT_CASE_LABELS[TEXT_CASES.LOWERCASE] },
  { value: TEXT_CASES.UPPERCASE, label: TEXT_CASE_LABELS[TEXT_CASES.UPPERCASE] },
  { value: TEXT_CASES.CAPITALIZE, label: TEXT_CASE_LABELS[TEXT_CASES.CAPITALIZE] },
  { value: TEXT_CASES.SNAKE_CASE, label: TEXT_CASE_LABELS[TEXT_CASES.SNAKE_CASE] },
  { value: TEXT_CASES.CAMEL_CASE, label: TEXT_CASE_LABELS[TEXT_CASES.CAMEL_CASE] },
];

export const DEFAULT_TEXT_CASE = TEXT_CASES.RESPECT_CASE;
