import { ThemeProvider } from '@/components/ui/theme-provider'

import type { Metadata } from 'next'

import './globals.css'
import WagmiWrapper from '@/providers/wagmi'
import SessionWrapper from '@/providers/session'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionWrapper>
          <WagmiWrapper>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              {children}
            </ThemeProvider>
          </WagmiWrapper>
        </SessionWrapper>
      </body>
    </html>
  )
}
